FROM jenkins/jenkins:2.479.3-jdk21

USER jenkins
RUN jenkins-plugin-cli --plugins \
    blueocean:1.27.25 \
    build-timestamp:1.1.1 \
    timestamper:1.30 \
    pollscm:1.9 \
    github-api:1.330-492.v3941a_032db_2a_ \
    token-macro:444.v52de7e9c573d \
    json-path-api:2.9.0-138.vc943da_d833b_6 \
    favorite:2.253.v9b_413168133b_
USER root
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}

COPY ./requirements.txt requirements.txt

RUN apt update && \
    apt install -y python3 python3-pip python3-venv

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy
